/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 'Rance03.exe'
*/

#define __int8 char
#define __int16 short
#define __int32 int
#define __int64 long long

struct HWND__;
struct tagSCROLLINFO;
struct _ITEMIDLIST;
struct HINSTANCE__;
struct HDC__;
struct _TBBUTTON;
union _LARGE_INTEGER;
struct HIMC__;
struct tagCANDIDATELIST;
struct HMENU__;
struct tagMENUITEMINFOA;
struct HBITMAP__;
struct tagWINDOWPLACEMENT;
struct tagCHOOSECOLORA;
struct HKEY__;
struct tagLOGFONTA;
struct tagWNDCLASSA;
struct HICON__;
struct HBRUSH__;
struct HRSRC__;
struct _SECURITY_ATTRIBUTES;
struct _EXCEPTION_RECORD;
struct _RTL_CRITICAL_SECTION;
struct _RTL_CRITICAL_SECTION_DEBUG;
struct __crt_locale_pointers;
struct _s_ThrowInfo;
struct _s_CatchableTypeArray;
struct _s_CatchableType;
struct TypeDescriptor;
struct _EXCEPTION_POINTERS;
struct _CONTEXT;
struct _iobuf;
struct $BA519187DB4FB038EDB1959BB4D2DF27;
struct $E6A349E6C594207448DC3F8A57F3A91C;
struct _GUID;

/* 1 */
typedef void *PVOID;

/* 2 */
typedef unsigned int DWORD;

/* 3 */
typedef struct _SCOPETABLE_ENTRY *PSCOPETABLE_ENTRY;

/* 4 */
struct _EH3_EXCEPTION_REGISTRATION
{
  struct _EH3_EXCEPTION_REGISTRATION *Next;
  PVOID ExceptionHandler;
  PSCOPETABLE_ENTRY ScopeTable;
  DWORD TryLevel;
};

/* 5 */
typedef struct _EH3_EXCEPTION_REGISTRATION EH3_EXCEPTION_REGISTRATION;

/* 6 */
typedef struct _EH3_EXCEPTION_REGISTRATION *PEH3_EXCEPTION_REGISTRATION;

/* 7 */
struct EXCEPTION_POINTERS;

/* 8 */
struct CPPEH_RECORD
{
  DWORD old_esp;
  EXCEPTION_POINTERS *exc_ptr;
  struct _EH3_EXCEPTION_REGISTRATION registration;
};

/* 9 */
enum __bitmask __TI_flags
{
  TI_IsConst = 0x1,
  TI_IsVolatile = 0x2,
  TI_IsUnaligned = 0x4,
  TI_IsPure = 0x8,
  TI_IsWinRT = 0x10,
};

/* 10 */
enum __bitmask __CT_flags
{
  CT_IsSimpleType = 0x1,
  CT_ByReferenceOnly = 0x2,
  CT_HasVirtualBase = 0x4,
  CT_IsWinRTHandle = 0x8,
  CT_IsStdBadAlloc = 0x10,
};

/* 11 */
struct _EH4_SCOPETABLE_RECORD
{
  int EnclosingLevel;
  void *FilterFunc;
  void *HandlerFunc;
};

/* 12 */
struct _EH4_SCOPETABLE
{
  DWORD GSCookieOffset;
  DWORD GSCookieXOROffset;
  DWORD EHCookieOffset;
  DWORD EHCookieXOROffset;
  struct _EH4_SCOPETABLE_RECORD ScopeRecord[];
};

/* 13 */
typedef struct HWND__ *HWND;

/* 14 */
struct HWND__
{
  int unused;
};

/* 16 */
typedef int LONG;

/* 15 */
struct tagPOINT
{
  LONG x;
  LONG y;
};

/* 17 */
typedef struct tagSCROLLINFO SCROLLINFO;

/* 19 */
typedef unsigned int UINT;

/* 18 */
struct tagSCROLLINFO
{
  UINT cbSize;
  UINT fMask;
  int nMin;
  int nMax;
  UINT nPage;
  int nPos;
  int nTrackPos;
};

/* 21 */
typedef int LONG_PTR;

/* 20 */
typedef LONG_PTR LPARAM;

/* 24 */
typedef struct _ITEMIDLIST ITEMIDLIST;

/* 23 */
typedef const ITEMIDLIST *LPCITEMIDLIST;

/* 31 */
typedef char CHAR;

/* 30 */
typedef CHAR *LPSTR;

/* 32 */
typedef const CHAR *LPCSTR;

/* 33 */
typedef int (__stdcall *BFFCALLBACK)(HWND hwnd, UINT uMsg, LPARAM lParam, LPARAM lpData);

/* 22 */
#pragma pack(push, 8)
struct _browseinfoA
{
  HWND hwndOwner;
  LPCITEMIDLIST pidlRoot;
  LPSTR pszDisplayName;
  LPCSTR lpszTitle;
  UINT ulFlags;
  BFFCALLBACK lpfn;
  LPARAM lParam;
  int iImage;
};
#pragma pack(pop)

/* 28 */
typedef unsigned __int16 USHORT;

/* 29 */
typedef unsigned __int8 BYTE;

/* 27 */
#pragma pack(push, 1)
struct _SHITEMID
{
  USHORT cb;
  BYTE abID[1];
};
#pragma pack(pop)

/* 26 */
typedef struct _SHITEMID SHITEMID;

/* 25 */
#pragma pack(push, 1)
struct _ITEMIDLIST
{
  SHITEMID mkid;
};
#pragma pack(pop)

/* 34 */
typedef struct HINSTANCE__ *HINSTANCE;

/* 35 */
struct HINSTANCE__
{
  int unused;
};

/* 36 */
struct tagRECT
{
  LONG left;
  LONG top;
  LONG right;
  LONG bottom;
};

/* 37 */
struct tagSIZE
{
  LONG cx;
  LONG cy;
};

/* 38 */
typedef void *HGDIOBJ;

/* 39 */
typedef struct HDC__ *HDC;

/* 40 */
struct HDC__
{
  int unused;
};

/* 41 */
typedef struct _TBBUTTON TBBUTTON;

/* 44 */
typedef unsigned int ULONG_PTR;

/* 43 */
typedef ULONG_PTR DWORD_PTR;

/* 45 */
typedef int INT_PTR;

/* 42 */
struct _TBBUTTON
{
  int iBitmap;
  int idCommand;
  BYTE fsState;
  BYTE fsStyle;
  BYTE bReserved[2];
  DWORD_PTR dwData;
  INT_PTR iString;
};

/* 46 */
typedef DWORD COLORREF;

/* 47 */
typedef struct tagRECT RECT;

/* 50 */
struct _FILETIME
{
  DWORD dwLowDateTime;
  DWORD dwHighDateTime;
};

/* 49 */
typedef struct _FILETIME FILETIME;

/* 48 */
struct _WIN32_FIND_DATAA
{
  DWORD dwFileAttributes;
  FILETIME ftCreationTime;
  FILETIME ftLastAccessTime;
  FILETIME ftLastWriteTime;
  DWORD nFileSizeHigh;
  DWORD nFileSizeLow;
  DWORD dwReserved0;
  DWORD dwReserved1;
  CHAR cFileName[260];
  CHAR cAlternateFileName[14];
};

/* 51 */
typedef void *HANDLE;

/* 52 */
typedef union _LARGE_INTEGER LARGE_INTEGER;

/* 54 */
struct _LARGE_INTEGER::$837407842DC9087486FDFA5FEB63B74E
{
  DWORD LowPart;
  LONG HighPart;
};

/* 55 */
typedef __int64 LONGLONG;

/* 53 */
union _LARGE_INTEGER
{
  struct
  {
    DWORD LowPart;
    LONG HighPart;
  };
  struct _LARGE_INTEGER::$837407842DC9087486FDFA5FEB63B74E u;
  LONGLONG QuadPart;
};

/* 56 */
typedef void *LPVOID;

/* 58 */
typedef unsigned int UINT_PTR;

/* 57 */
typedef UINT_PTR WPARAM;

/* 59 */
typedef struct HIMC__ *HIMC;

/* 60 */
struct HIMC__
{
  int unused;
};

/* 61 */
typedef struct tagCANDIDATELIST *LPCANDIDATELIST;

/* 62 */
struct tagCANDIDATELIST
{
  DWORD dwSize;
  DWORD dwStyle;
  DWORD dwCount;
  DWORD dwSelection;
  DWORD dwPageStart;
  DWORD dwPageSize;
  DWORD dwOffset[1];
};

/* 63 */
typedef struct HMENU__ *HMENU;

/* 64 */
struct HMENU__
{
  int unused;
};

/* 65 */
typedef struct tagMENUITEMINFOA MENUITEMINFOA;

/* 67 */
typedef struct HBITMAP__ *HBITMAP;

/* 66 */
struct tagMENUITEMINFOA
{
  UINT cbSize;
  UINT fMask;
  UINT fType;
  UINT fState;
  UINT wID;
  HMENU hSubMenu;
  HBITMAP hbmpChecked;
  HBITMAP hbmpUnchecked;
  ULONG_PTR dwItemData;
  LPSTR dwTypeData;
  UINT cch;
  HBITMAP hbmpItem;
};

/* 68 */
struct HBITMAP__
{
  int unused;
};

/* 71 */
typedef unsigned __int64 ULONGLONG;

/* 70 */
typedef ULONGLONG DWORDLONG;

/* 69 */
struct _MEMORYSTATUSEX
{
  DWORD dwLength;
  DWORD dwMemoryLoad;
  DWORDLONG ullTotalPhys;
  DWORDLONG ullAvailPhys;
  DWORDLONG ullTotalPageFile;
  DWORDLONG ullAvailPageFile;
  DWORDLONG ullTotalVirtual;
  DWORDLONG ullAvailVirtual;
  DWORDLONG ullAvailExtendedVirtual;
};

/* 73 */
typedef unsigned __int16 WORD;

/* 72 */
struct _SYSTEMTIME
{
  WORD wYear;
  WORD wMonth;
  WORD wDayOfWeek;
  WORD wDay;
  WORD wHour;
  WORD wMinute;
  WORD wSecond;
  WORD wMilliseconds;
};

/* 74 */
typedef const void *LPCVOID;

/* 76 */
typedef int BOOL;

/* 75 */
struct tagPAINTSTRUCT
{
  HDC hdc;
  BOOL fErase;
  RECT rcPaint;
  BOOL fRestore;
  BOOL fIncUpdate;
  BYTE rgbReserved[32];
};

/* 77 */
struct tagTRACKMOUSEEVENT
{
  DWORD cbSize;
  DWORD dwFlags;
  HWND hwndTrack;
  DWORD dwHoverTime;
};

/* 78 */
typedef struct tagWINDOWPLACEMENT WINDOWPLACEMENT;

/* 80 */
typedef struct tagPOINT POINT;

/* 79 */
struct tagWINDOWPLACEMENT
{
  UINT length;
  UINT flags;
  UINT showCmd;
  POINT ptMinPosition;
  POINT ptMaxPosition;
  RECT rcNormalPosition;
};

/* 81 */
typedef struct tagCHOOSECOLORA *LPCHOOSECOLORA;

/* 83 */
typedef UINT_PTR (__stdcall *LPCCHOOKPROC)(HWND, UINT, WPARAM, LPARAM);

/* 82 */
#pragma pack(push, 1)
struct tagCHOOSECOLORA
{
  DWORD lStructSize;
  HWND hwndOwner;
  HWND hInstance;
  COLORREF rgbResult;
  COLORREF *lpCustColors;
  DWORD Flags;
  LPARAM lCustData;
  LPCCHOOKPROC lpfnHook;
  LPCSTR lpTemplateName;
};
#pragma pack(pop)

/* 84 */
typedef struct HKEY__ *HKEY;

/* 85 */
struct HKEY__
{
  int unused;
};

/* 86 */
typedef struct tagLOGFONTA LOGFONTA;

/* 87 */
struct tagLOGFONTA
{
  LONG lfHeight;
  LONG lfWidth;
  LONG lfEscapement;
  LONG lfOrientation;
  LONG lfWeight;
  BYTE lfItalic;
  BYTE lfUnderline;
  BYTE lfStrikeOut;
  BYTE lfCharSet;
  BYTE lfOutPrecision;
  BYTE lfClipPrecision;
  BYTE lfQuality;
  BYTE lfPitchAndFamily;
  CHAR lfFaceName[32];
};

/* 88 */
typedef BYTE *LPBYTE;

/* 89 */
typedef struct tagWNDCLASSA WNDCLASSA;

/* 92 */
typedef LONG_PTR LRESULT;

/* 91 */
typedef LRESULT (__stdcall *WNDPROC)(HWND, UINT, WPARAM, LPARAM);

/* 93 */
typedef struct HICON__ *HICON;

/* 95 */
typedef HICON HCURSOR;

/* 96 */
typedef struct HBRUSH__ *HBRUSH;

/* 90 */
struct tagWNDCLASSA
{
  UINT style;
  WNDPROC lpfnWndProc;
  int cbClsExtra;
  int cbWndExtra;
  HINSTANCE hInstance;
  HICON hIcon;
  HCURSOR hCursor;
  HBRUSH hbrBackground;
  LPCSTR lpszMenuName;
  LPCSTR lpszClassName;
};

/* 94 */
struct HICON__
{
  int unused;
};

/* 97 */
struct HBRUSH__
{
  int unused;
};

/* 98 */
typedef struct HRSRC__ *HRSRC;

/* 99 */
struct HRSRC__
{
  int unused;
};

/* 100 */
struct _OSVERSIONINFOEXA
{
  DWORD dwOSVersionInfoSize;
  DWORD dwMajorVersion;
  DWORD dwMinorVersion;
  DWORD dwBuildNumber;
  DWORD dwPlatformId;
  CHAR szCSDVersion[128];
  WORD wServicePackMajor;
  WORD wServicePackMinor;
  WORD wSuiteMask;
  BYTE wProductType;
  BYTE wReserved;
};

/* 101 */
typedef struct _SECURITY_ATTRIBUTES *LPSECURITY_ATTRIBUTES;

/* 102 */
struct _SECURITY_ATTRIBUTES
{
  DWORD nLength;
  LPVOID lpSecurityDescriptor;
  BOOL bInheritHandle;
};

/* 103 */
typedef ULONG_PTR SIZE_T;

/* 104 */
typedef DWORD *LPDWORD;

/* 105 */
typedef struct _EXCEPTION_RECORD EXCEPTION_RECORD;

/* 106 */
struct _EXCEPTION_RECORD
{
  DWORD ExceptionCode;
  DWORD ExceptionFlags;
  struct _EXCEPTION_RECORD *ExceptionRecord;
  PVOID ExceptionAddress;
  DWORD NumberParameters;
  ULONG_PTR ExceptionInformation[15];
};

/* 107 */
typedef HINSTANCE HMODULE;

/* 108 */
typedef EXCEPTION_RECORD *PEXCEPTION_RECORD;

/* 112 */
typedef unsigned __int16 wchar_t;

/* 111 */
typedef wchar_t WCHAR;

/* 110 */
typedef WCHAR *LPWSTR;

/* 109 */
struct _STARTUPINFOW
{
  DWORD cb;
  LPWSTR lpReserved;
  LPWSTR lpDesktop;
  LPWSTR lpTitle;
  DWORD dwX;
  DWORD dwY;
  DWORD dwXSize;
  DWORD dwYSize;
  DWORD dwXCountChars;
  DWORD dwYCountChars;
  DWORD dwFillAttribute;
  DWORD dwFlags;
  WORD wShowWindow;
  WORD cbReserved2;
  LPBYTE lpReserved2;
  HANDLE hStdInput;
  HANDLE hStdOutput;
  HANDLE hStdError;
};

/* 114 */
typedef struct _RTL_CRITICAL_SECTION *PRTL_CRITICAL_SECTION;

/* 113 */
typedef PRTL_CRITICAL_SECTION LPCRITICAL_SECTION;

/* 116 */
typedef struct _RTL_CRITICAL_SECTION_DEBUG *PRTL_CRITICAL_SECTION_DEBUG;

/* 115 */
#pragma pack(push, 8)
struct _RTL_CRITICAL_SECTION
{
  PRTL_CRITICAL_SECTION_DEBUG DebugInfo;
  LONG LockCount;
  LONG RecursionCount;
  HANDLE OwningThread;
  HANDLE LockSemaphore;
  ULONG_PTR SpinCount;
};
#pragma pack(pop)

/* 119 */
struct _LIST_ENTRY
{
  struct _LIST_ENTRY *Flink;
  struct _LIST_ENTRY *Blink;
};

/* 118 */
typedef struct _LIST_ENTRY LIST_ENTRY;

/* 117 */
struct _RTL_CRITICAL_SECTION_DEBUG
{
  WORD Type;
  WORD CreatorBackTraceIndex;
  struct _RTL_CRITICAL_SECTION *CriticalSection;
  LIST_ENTRY ProcessLocksList;
  DWORD EntryCount;
  DWORD ContentionCount;
  DWORD Flags;
  WORD CreatorBackTraceIndexHigh;
  WORD SpareWORD;
};

/* 121 */
typedef struct _SYSTEMTIME SYSTEMTIME;

/* 120 */
struct _TIME_ZONE_INFORMATION
{
  LONG Bias;
  WCHAR StandardName[32];
  SYSTEMTIME StandardDate;
  LONG StandardBias;
  WCHAR DaylightName[32];
  SYSTEMTIME DaylightDate;
  LONG DaylightBias;
};

/* 122 */
typedef const CHAR *LPCCH;

/* 123 */
struct _cpinfo
{
  UINT MaxCharSize;
  BYTE DefaultChar[2];
  BYTE LeadByte[12];
};

/* 124 */
typedef const WCHAR *PCNZWCH;

/* 125 */
typedef const WCHAR *LPCWSTR;

/* 126 */
typedef WORD *LPWORD;

/* 127 */
typedef int (__cdecl *_onexit_t)();

/* 128 */
typedef unsigned int size_t;

/* 129 */
typedef __crt_locale_pointers *_locale_t;

/* 130 */
#pragma pack(push, 8)
struct __crt_locale_pointers
{
  struct __crt_locale_data *locinfo;
  struct __crt_multibyte_data *mbcinfo;
};
#pragma pack(pop)

/* 131 */
typedef char *va_list;

/* 132 */
typedef size_t rsize_t;

/* 133 */
typedef unsigned int (__stdcall *_beginthreadex_proc_type)(void *);

/* 134 */
typedef __int64 __time64_t;

/* 135 */
typedef int (__cdecl *_CoreCrtNonSecureSearchSortCompareFunction)(const void *, const void *);

/* 137 */
typedef const struct _s_ThrowInfo ThrowInfo;

/* 136 */
typedef ThrowInfo _ThrowInfo;

/* 139 */
typedef void (__cdecl *PMFN)(void *);

/* 140 */
typedef const struct _s_CatchableTypeArray CatchableTypeArray;

/* 138 */
#pragma pack(push, 4)
struct _s_ThrowInfo
{
  unsigned int attributes;
  PMFN pmfnUnwind;
  int (__cdecl *pForwardCompat)();
  CatchableTypeArray *pCatchableTypeArray;
};
#pragma pack(pop)

/* 142 */
typedef const struct _s_CatchableType CatchableType;

/* 141 */
#pragma pack(push, 4)
struct _s_CatchableTypeArray
{
  int nCatchableTypes;
  CatchableType *arrayOfCatchableTypes[];
};
#pragma pack(pop)

/* 145 */
#pragma pack(push, 4)
struct PMD
{
  int mdisp;
  int pdisp;
  int vdisp;
};
#pragma pack(pop)

/* 143 */
#pragma pack(push, 4)
struct _s_CatchableType
{
  unsigned int properties;
  TypeDescriptor *pType;
  PMD thisDisplacement;
  int sizeOrOffset;
  PMFN copyFunction;
};
#pragma pack(pop)

/* 144 */
struct TypeDescriptor
{
  const struct TypeDescriptor_vtbl *__vftable /*VFT*/;
  void *spare;
  char name[] __strlit(C,"windows-1252");
};

/* 147 */
typedef LONG (__stdcall *PTOP_LEVEL_EXCEPTION_FILTER)(struct _EXCEPTION_POINTERS *ExceptionInfo);

/* 146 */
typedef PTOP_LEVEL_EXCEPTION_FILTER LPTOP_LEVEL_EXCEPTION_FILTER;

/* 150 */
typedef struct _CONTEXT CONTEXT;

/* 149 */
typedef CONTEXT *PCONTEXT;

/* 148 */
struct _EXCEPTION_POINTERS
{
  PEXCEPTION_RECORD ExceptionRecord;
  PCONTEXT ContextRecord;
};

/* 153 */
struct _FLOATING_SAVE_AREA
{
  DWORD ControlWord;
  DWORD StatusWord;
  DWORD TagWord;
  DWORD ErrorOffset;
  DWORD ErrorSelector;
  DWORD DataOffset;
  DWORD DataSelector;
  BYTE RegisterArea[80];
  DWORD Spare0;
};

/* 152 */
typedef struct _FLOATING_SAVE_AREA FLOATING_SAVE_AREA;

/* 151 */
#pragma pack(push, 4)
struct _CONTEXT
{
  DWORD ContextFlags;
  DWORD Dr0;
  DWORD Dr1;
  DWORD Dr2;
  DWORD Dr3;
  DWORD Dr6;
  DWORD Dr7;
  FLOATING_SAVE_AREA FloatSave;
  DWORD SegGs;
  DWORD SegFs;
  DWORD SegEs;
  DWORD SegDs;
  DWORD Edi;
  DWORD Esi;
  DWORD Ebx;
  DWORD Edx;
  DWORD Ecx;
  DWORD Eax;
  DWORD Ebp;
  DWORD Eip;
  DWORD SegCs;
  DWORD EFlags;
  DWORD Esp;
  DWORD SegSs;
  BYTE ExtendedRegisters[512];
};
#pragma pack(pop)

/* 154 */
typedef unsigned int uintptr_t;

/* 155 */
typedef struct _iobuf FILE;

/* 156 */
struct _iobuf
{
  char *_ptr;
  int _cnt;
  char *_base;
  int _flag;
  int _file;
  int _charbuf;
  int _bufsiz;
  char *_tmpfname;
};

/* 157 */
typedef struct $BA519187DB4FB038EDB1959BB4D2DF27 _CRT_DOUBLE;

/* 158 */
#pragma pack(push, 8)
struct $BA519187DB4FB038EDB1959BB4D2DF27
{
  double x;
};
#pragma pack(pop)

/* 159 */
typedef struct $E6A349E6C594207448DC3F8A57F3A91C _CRT_FLOAT;

/* 160 */
#pragma pack(push, 8)
struct $E6A349E6C594207448DC3F8A57F3A91C
{
  float f;
};
#pragma pack(pop)

/* 161 */
struct FuncInfo
{
  unsigned __int32 magicNumber : 29;
  unsigned __int32 bbtFlags : 3;
  int maxState __dec;
  void *pUnwindMap;
  int nTryBlocks __dec;
  void *pTryBlockMap;
  int nIPMapEntries __dec;
  void *pIPtoStateMap;
  void *pESTypeList;
  int EHFlags __hex;
};

/* 162 */
struct UnwindMapEntry
{
  int toState __dec;
  void *action;
};

/* 163 */
struct TryBlockMapEntry
{
  int tryLow __dec;
  int tryHigh __dec;
  int catchHigh __dec;
  int nCatches __dec;
  void *pHandlerArray;
};

/* 164 */
struct HandlerType
{
  int adjectives __hex;
  const struct TypeDescriptor *pType;
  int dispCatchObj __dec;
  void *addressOfHandler;
};

/* 166 */
typedef struct _GUID GUID;

/* 165 */
typedef GUID IID;

/* 167 */
struct _GUID
{
  unsigned int Data1;
  unsigned __int16 Data2;
  unsigned __int16 Data3;
  unsigned __int8 Data4[8];
};

/* 168 */
struct tagMSG
{
  HWND hwnd;
  UINT message;
  WPARAM wParam;
  LPARAM lParam;
  DWORD time;
  POINT pt;
};

/* 169 */
struct Concurrency::details::ContextBase;

/* 170 */
struct Concurrency::details::SchedulerBase;

/* 171 */
struct Concurrency::details::TaskStack;

/* 172 */
struct Concurrency::details::VirtualProcessor;

/* 173 */
struct Concurrency::details::ExternalContextBase;

/* 174 */
struct Concurrency::details::SchedulerProxy;

/* 175 */
struct Concurrency::details::SchedulingRing;

/* 176 */
struct Concurrency::details::UMSThreadVirtualProcessor;

/* 177 */
struct Concurrency::details::ScheduleGroupSegmentBase;

/* 178 */
struct std::exception;

/* 179 */
struct exception;

/* 181 */
typedef int __ehstate_t;

/* 180 */
#pragma pack(push, 4)
struct EHRegistrationNode
{
  EHRegistrationNode *pNext;
  void *frameHandler;
  __ehstate_t state;
};
#pragma pack(pop)

/* 182 */
struct std::nothrow_t;

/* 183 */
struct _LocaleUpdate;

